name: cross build for pi

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: arm-unknown-linux-musleabihf
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rustup
        run: rustup target add ${{ matrix.target }}

      - name: Set up cross compiler
        run: cargo install cross

      - name: Build
        run: cd backend && cross build --release --target ${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: piexe
          path: backend/target/${{ matrix.target }}/release/backend
